# Generated by Django 2.1.5 on 2023-04-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('four_s', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='card_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
